create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  family_id uuid references public.families(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  event_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_family_created_idx
  on public.analytics_events (family_id, created_at desc);

create index if not exists analytics_events_event_created_idx
  on public.analytics_events (event_name, created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "Users can insert own analytics events"
on public.analytics_events;

create policy "Users can insert own analytics events"
on public.analytics_events
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    family_id is null
    or exists (
      select 1
      from public.family_members fm
      where fm.family_id = analytics_events.family_id
        and fm.user_id = auth.uid()
    )
  )
);

revoke update, delete on public.analytics_events from authenticated;
grant insert on public.analytics_events to authenticated;